[package]
name = "forenx-secure-eraser"
version = "0.1.0"
publish = false
description = "ForenX Secure Eraser Desktop Application"
authors = ["ForenX Team"]
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
drive_eraser = { path = "../crates/drive_eraser" }
file_eraser = { path = "../crates/file_eraser" }
log = "0.4.34"
tauri-plugin-log = "2.9.1"
tauri-plugin-dialog = "2.7.3"

[build-dependencies]
tauri-build = { version = "2", features = [] }
